# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first scene.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class init_scene(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(691, 415)
        Form.setFixedSize(691, 415)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(25, 25, 636, 371))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("figure/decryption_first_sceen.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textinput = QtWidgets.QTextBrowser(Form)
        self.textinput.setGeometry(QtCore.QRect(130, 245, 91, 31))
        self.textinput.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.textinput.setObjectName("textinput")
        self.textoutput = QtWidgets.QTextBrowser(Form)
        self.textoutput.setGeometry(QtCore.QRect(490, 245, 91, 31))
        self.textoutput.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.textoutput.setObjectName("textoutput")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 130, 226, 121))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:transparent;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = init_scene()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
