# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key_generation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keygeneration(object):
    def setupUi(self, keygeneration):
        keygeneration.setObjectName("keygeneration")
        keygeneration.resize(872, 446)
        self.label = QtWidgets.QLabel(keygeneration)
        self.label.setGeometry(QtCore.QRect(35, 15, 821, 416))
        self.label.setStyleSheet("QLabel{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(keygeneration)
        self.label_3.setGeometry(QtCore.QRect(80, 100, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("figure/key.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.keyinput = QtWidgets.QTextBrowser(keygeneration)
        self.keyinput.setGeometry(QtCore.QRect(70, 170, 91, 31))
        self.keyinput.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.keyinput.setPlaceholderText("")
        self.keyinput.setObjectName("keyinput")
        self.P10 = QtWidgets.QTextBrowser(keygeneration)
        self.P10.setGeometry(QtCore.QRect(225, 120, 91, 31))
        self.P10.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.P10.setObjectName("P10")
        self.shift1 = QtWidgets.QTextBrowser(keygeneration)
        self.shift1.setGeometry(QtCore.QRect(350, 80, 91, 31))
        self.shift1.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.shift1.setObjectName("shift1")
        self.shift1_2 = QtWidgets.QTextBrowser(keygeneration)
        self.shift1_2.setGeometry(QtCore.QRect(345, 155, 91, 31))
        self.shift1_2.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.shift1_2.setObjectName("shift1_2")
        self.P8 = QtWidgets.QTextBrowser(keygeneration)
        self.P8.setGeometry(QtCore.QRect(475, 120, 91, 31))
        self.P8.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.P8.setObjectName("P8")
        self.label_2 = QtWidgets.QLabel(keygeneration)
        self.label_2.setGeometry(QtCore.QRect(170, 85, 641, 286))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("figure/key gengration structure.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.P8_2 = QtWidgets.QTextBrowser(keygeneration)
        self.P8_2.setGeometry(QtCore.QRect(730, 120, 91, 31))
        self.P8_2.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.P8_2.setObjectName("P8_2")
        self.shift2 = QtWidgets.QTextBrowser(keygeneration)
        self.shift2.setGeometry(QtCore.QRect(600, 80, 91, 31))
        self.shift2.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.shift2.setObjectName("shift2")
        self.shift2_2 = QtWidgets.QTextBrowser(keygeneration)
        self.shift2_2.setGeometry(QtCore.QRect(600, 155, 91, 31))
        self.shift2_2.setStyleSheet("QTextBrowser{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"background:#e7e6e6;\n"
"}")
        self.shift2_2.setObjectName("shift2_2")
        self.des_button = QtWidgets.QPushButton(keygeneration)
        self.des_button.setGeometry(QtCore.QRect(460, 235, 276, 131))
        self.des_button.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"}")
        self.des_button.setText("")
        self.des_button.setObjectName("des_button")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.keyinput.raise_()
        self.P10.raise_()
        self.shift1.raise_()
        self.shift1_2.raise_()
        self.P8.raise_()
        self.P8_2.raise_()
        self.shift2.raise_()
        self.shift2_2.raise_()
        self.des_button.raise_()

        self.retranslateUi(keygeneration)
        QtCore.QMetaObject.connectSlotsByName(keygeneration)

    def retranslateUi(self, keygeneration):
        _translate = QtCore.QCoreApplication.translate
        keygeneration.setWindowTitle(_translate("keygeneration", "key generation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    keygeneration = QtWidgets.QWidget()
    ui = Ui_keygeneration()
    ui.setupUi(keygeneration)
    keygeneration.show()
    sys.exit(app.exec_())
