# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(466, 280)
        MainWindow.setFixedSize(466, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 431, 251))
        self.label.setStyleSheet("QLabel{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")

        
        self.textinput = QtWidgets.QLineEdit(self.centralwidget)
        self.textinput.setGeometry(QtCore.QRect(180, 40, 241, 31))
        self.textinput.setStyleSheet("QLineEdit{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"}")
        self.textinput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textinput.setInputMask("")
        self.textinput.setClearButtonEnabled(False)
        self.textinput.setObjectName("textinput")
        
        self.keyinput = QtWidgets.QLineEdit(self.centralwidget)
        self.keyinput.setGeometry(QtCore.QRect(180, 120, 241, 31))
        self.keyinput.setStyleSheet("QLineEdit{\n"
"border: 2px solid gray;\n"
"border-radius: 10px;\n"
"\n"
"}")
        self.keyinput.setObjectName("keyinput")

        self.EncryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.EncryptButton.setGeometry(QtCore.QRect(70, 190, 141, 41))
        self.EncryptButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.EncryptButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EncryptButton.setStyleSheet("QPushButton{\n"
"background:rgb(194, 210, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(153, 171, 203);\n"
"}")
        self.EncryptButton.setAutoDefault(False)
        self.EncryptButton.setObjectName("EncryptButton")

        self.DecryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.DecryptButton.setGeometry(QtCore.QRect(270, 190, 141, 41))
        self.DecryptButton.setStyleSheet("QPushButton{\n"
"background:rgb(218, 240, 203);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(169, 207, 150);\n"
"}")
        self.DecryptButton.setObjectName("DecryptButton")
        self.keylabel = QtWidgets.QLabel(self.centralwidget)
        self.keylabel.setGeometry(QtCore.QRect(60, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.keylabel.setFont(font)
        self.keylabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.keylabel.setTextFormat(QtCore.Qt.AutoText)
        self.keylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.keylabel.setWordWrap(False)
        self.keylabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.keylabel.setObjectName("keylabel")
        self.keylabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.keylabel_2.setGeometry(QtCore.QRect(20, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.keylabel_2.setFont(font)
        self.keylabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.keylabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.keylabel_2.setObjectName("keylabel_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 41, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("figure/files.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 110, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("figure/key.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.condition_label = QtWidgets.QLabel(self.centralwidget)
        self.condition_label.setGeometry(QtCore.QRect(160, 160, 221, 21))
        self.condition_label.setText("")
        self.condition_label.setObjectName("condition_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EncryptButton.setText(_translate("MainWindow", "encrypt"))
        self.keyinput.setPlaceholderText(_translate("MainWindow", "input 10 bits"))
        self.textinput.setPlaceholderText(_translate("MainWindow", "input 8 bits"))
        self.DecryptButton.setText(_translate("MainWindow", "decrypt"))
        self.keylabel.setText(_translate("MainWindow", "key"))
        self.keylabel_2.setText(_translate("MainWindow", "plaintext or ciphertext"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
