# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(991, 574)
        Form.setFixedSize(991, 574)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(15, 20, 966, 536))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("figure/decryption_structure.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.IP_inverse = QtWidgets.QLabel(Form)
        self.IP_inverse.setGeometry(QtCore.QRect(180, 405, 81, 21))
        self.IP_inverse.setObjectName("IP_inverse")
        self.textinput = QtWidgets.QLabel(Form)
        self.textinput.setGeometry(QtCore.QRect(40, 280, 96, 26))
        self.textinput.setObjectName("textinput")
        self.IP = QtWidgets.QLabel(Form)
        self.IP.setGeometry(QtCore.QRect(195, 265, 71, 21))
        self.IP.setObjectName("IP")
        self.EP_1 = QtWidgets.QLabel(Form)
        self.EP_1.setGeometry(QtCore.QRect(265, 160, 81, 21))
        self.EP_1.setObjectName("EP_1")
        self.EP_2 = QtWidgets.QLabel(Form)
        self.EP_2.setGeometry(QtCore.QRect(820, 175, 81, 21))
        self.EP_2.setObjectName("EP_2")
        self.P4_1 = QtWidgets.QLabel(Form)
        self.P4_1.setGeometry(QtCore.QRect(585, 170, 81, 21))
        self.P4_1.setObjectName("P4_1")
        self.P4_2 = QtWidgets.QLabel(Form)
        self.P4_2.setGeometry(QtCore.QRect(825, 400, 81, 21))
        self.P4_2.setObjectName("P4_2")
        self.textoutput = QtWidgets.QLabel(Form)
        self.textoutput.setGeometry(QtCore.QRect(40, 440, 96, 26))
        self.textoutput.setObjectName("textoutput")
        self.S0_1 = QtWidgets.QLabel(Form)
        self.S0_1.setGeometry(QtCore.QRect(505, 155, 36, 16))
        self.S0_1.setObjectName("S0_1")
        self.S1_1 = QtWidgets.QLabel(Form)
        self.S1_1.setGeometry(QtCore.QRect(505, 190, 36, 16))
        self.S1_1.setObjectName("S1_1")
        self.S0_2 = QtWidgets.QLabel(Form)
        self.S0_2.setGeometry(QtCore.QRect(825, 340, 36, 16))
        self.S0_2.setObjectName("S0_2")
        self.S1_2 = QtWidgets.QLabel(Form)
        self.S1_2.setGeometry(QtCore.QRect(880, 340, 36, 16))
        self.S1_2.setObjectName("S1_2")
        self.key_button = QtWidgets.QPushButton(Form)
        self.key_button.setGeometry(QtCore.QRect(370, 40, 211, 46))
        self.key_button.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"}")
        self.key_button.setText("")
        self.key_button.setObjectName("key_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.IP_inverse.setText(_translate("Form", "IP_inverse"))
        self.textinput.setText(_translate("Form", "textinput"))
        self.IP.setText(_translate("Form", "IP"))
        self.EP_1.setText(_translate("Form", "EP_1"))
        self.EP_2.setText(_translate("Form", "EP_2"))
        self.P4_1.setText(_translate("Form", "P4_1"))
        self.P4_2.setText(_translate("Form", "P4_2"))
        self.textoutput.setText(_translate("Form", "textoutput"))
        self.S0_1.setText(_translate("Form", "S0_1"))
        self.S1_1.setText(_translate("Form", "S1_1"))
        self.S0_2.setText(_translate("Form", "S0_2"))
        self.S1_2.setText(_translate("Form", "S1_2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
